version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rayon
    versions:
    - "> 1.5.0, < 2"
  - dependency-name: ahash
    versions:
    - "> 0.7.0, < 0.8"
  - dependency-name: anyhow
    versions:
    - "> 1.0.38, < 2"
  - dependency-name: regex
    versions:
    - "> 1.4.3, < 2"
